/**
 * Re-export generated OpenAPI types from shared package (single source of truth).
 *
 * The schema is auto-generated by openapi-typescript in @volleykit/shared.
 * Run `pnpm run generate:api` from root to regenerate.
 */
export type { components } from '@volleykit/shared/api'
